version: '3.8'

services:
  my_container:
    image: hugo0.138.0_image
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hugo-learning-notebook
    volumes:
      - ./:/app  # 将本地目录映射到容器内的 /app 目录
    ports:
      - "1313:1313"  # 将主机的 1313 端口映射到容器的 1313 端口
    command: hugo server -p 1313 --baseURL "http://172.18.55.72:1313" --bind=0.0.0.0  # 容器启动后执行的命令
    restart: always  # 设置自动重启策略

# docker-compose up -d